### ISSUE TITLE
TypeErrors when running example2d_parallel.py

### ISSUE THREAD

**Issue by rcabell** [krober10nd/simple_cgal#5]
Hello! I'm hoping to leverage your excellent work parallelizing the Delaunay triangularization for use with the SCHISM model, but am running into an apparent Numpy-related issue with trying the example:

```Traceback (most recent call last):
  File "example2d_parallel.py", line 55, in <module>
    exports = utils.enqueue(extents, points, tria.vertices, rank, size)
  File "/glade/scratch/rcabell/simple_cgal/examples/utils/migration.py", line 75, in enqueue
    exports = cutils.where_to2(points, faces, le, re, rank)
TypeError: where_to2(): incompatible function arguments. The following argument types are supported:
    1. (arg0: numpy.ndarray[float64], arg1: numpy.ndarray[int32], arg2: numpy.ndarray[int32], arg3: numpy.ndarray[int32], arg4: numpy.ndarray[float64], arg5: numpy.ndarray[float64], arg6: int) -> array
```

Since the code is about a year old at this point (June 2021), it's possible this is due to an incompatibility with a newer version of Numpy (I'm using v1.17.4). Can you tell me what version you originally developed against? Thanks!

**Comment by krober10nd** [comment]
Hey @rcabell this package was just a demo I had used to develop the parallel mesh generation algorithm that's now in SeismicMesh https://github.com/krober10nd/SeismicMesh 

For meshing for SCHISM (if you have MATLAB) I have a specific package for that here 
https://github.com/CHLNDDEV/OceanMesh2D

**Comment by rcabell** [comment]
Thanks! I appreciate the quick reply and I'll check out those two packages.
